

export const all_routes = {
  // dashboard routes
  dealsDashboard: "/dashboard/deals-dashboard",
  leadsDashboard: "/dashboard/leads-dashboard",
  projectDashboard: "/dashboard/project-dashboard",

  //Super Admin
  superadminDashboard:"/super-admin/dashboard",
  superadminCompany:"/super-admin/company",
  superadminSubscription:"/super-admin/subscription",
  superadminPackagelist:"/super-admin/packages",
  superadminPackageGrid:"/super-admin/packages-grid",
  superadminDomain:"/super-admin/domain",
  superadminPurchaseTransaction:"/super-admin/purchase-transaction",

  //crm routes
  activityCalls: "/crm/activity-calls",
  activityMail: "/crm/activity-mail",
  activityTask: "/crm/activity-task",
  activityMeeting: "/crm/activity-meeting",
  activities: "/crm/activities",
  payments: "/crm/payments",
  tasks: "/crm/tasks",
  tasksImportant: "/crm/tasks-important",
  tasksCompleted: "/crm/tasks-completed",
  campaign: "/crm/campaign",
  campaignComplete: "/crm/campaign-complete",
  campaignArchieve: "/crm/campaign-archieve",
  addCampaign: "/crm/addCampaign",
  analytics: "/crm/analytics",
  contactDetails: "/crm/contact-details",
  dealsGrid: "/crm/deals",
  dealsList: "/crm/deals-list",
  dealsDetails: "/crm/deals-details",
  contactList: "/crm/contact-list",
  leadsKanban: "/leads-kanban",
  pipeline: "/crm/pipeline",
  companyDetails: "/crm/company-details",
  projectDetails: "/crm/project-details",
  contactGrid: "/crm/contact-grid",
  companiesGrid: "/crm/companies-grid",
  companiesList:"/crm/companies-list",
  companiesDetails:"/crm/companies-details",
  compaignComplete: "/crm/compaign-complete",
  companies: "/companies",
  leadsDetails: "/leads-details",
  leads: "/leads",
  leadsList: "/leads-list",
  projectsGrid: "/crm/projects",
  projectsList: "/crm/project-list",
  ProposalsList: "/crm/proposals-list",
  ProposalsGrid: "/crm/proposals-grid",
  ProposalsView: "/crm/proposals-view",
  ContractsList: "/crm/contracts-list",
  ContractsGrid: "/crm/contracts-grid",
  InvoiceList:     "/crm/invoice-list",
  InvoiceGrid:     "/crm/invoice-grid",
  invoices:        "/invoices",
  newInvoice:      "/invoices/new",
  invoiceOverview:    "/invoices/:id",
  editInvoice:        "/invoices/:id/edit",
  recordPayment:      "/invoices/:id/payment",
  newCreditNote:      "/invoices/:id/credit-note",
  creditNotes:        "/credit-notes",
  creditNoteOverview: "/credit-notes/:id",
  newPayment:         "/payments/new",
  paymentOverview:      "/payments/:id",
  paymentRefund:        "/payments/:id/refund",
  paymentRefundEdit:    "/payments/:id/refunds/:refundId/edit",
  estimationList: "/crm/estimation-list",
  estimationKanban: "/crm/estimation-kanban",


  bankAccounts: "/bank-accounts",
  blankPage: "/blank-page",
  calendar: "/calendar",
  dataTables: "/data-tables",
  tablesBasic: "/tables-basic",
  notes: "/notes",
  comingSoon: "/coming-soon",

  // auth routes routes
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  twoStepVerification: "/two-step-verification",
  success: "/success",
  emailVerification: "/email-verification",
  lockScreen: "/lock-screen",
  resetPassword: "/reset-password",

  //ui routes
  alert: "/ui-alert",
  accordion: "/ui-accordion",
  avatar: "/ui-avatar",
  badges: "/ui-badges",
  border: "/ui-border",
  breadcrums: "/ui-breadcrums",
  button: "/ui-buttons",
  buttonGroup: "/ui-button-group",
  cards: "/ui-cards",
  carousel: "/ui-carousel",
  colors: "/ui-colors",
  dropdowns: "/ui-dropdowns",
  images: "/ui-images",
  lightbox: "/ui-lightbox",
  media: "/ui-media",
  modals: "/ui-modals",
  navTabs: "/ui-navtabs",
  offcanvas: "/ui-offcanvas",
  pagination: "/ui-pagination",
  placeholder: "/ui-placeholder",
  popover: "/ui-popover",
  progress: "/ui-progress",
  rangeSlider: "/ui-rangeslider",
  spinner: "/ui-spinner",
  sweetalert: "/ui-alert",
  toasts: "/ui-toasts",
  tooltip: "/ui-tooltip",
  typography: "/ui-typography",
  video: "/ui-video",
  clipboard: "/ui-clipboard",
  counter: "/ui-counter",
  dragandDrop: "/ui-drag-drop",
  rating: "/ui-rating",
  ribbon: "/ui-ribbon",
  stickyNotes: "/ui-sticky-notes",
  textEditor: "/ui-text-editor",
  timeLine: "/ui-timeline",
  scrollBar: "/ui-scrollbar",
  apexChat: "/ui-apexchat",
  featherIcons: "/ui-feather-icon",
  falgIcons: "/ui-flag-icon",
  fantawesome: "/ui-fantawesome",
  materialIcon: "/ui-material-icon",
  pe7icon: "/ui-icon-pe7",
  simpleLineIcon: "/ui-simpleline",
  themifyIcon: "/ui-themify",
  typicon: "/ui-typicon",
  weatherIcon: "/ui-weather-icon",
  basicInput: "/forms-basic-input",
  checkboxandRadios: "/form-checkbox-radios",
  inputGroup: "/form-input-groups",
  gridandGutters: "/form-grid-gutters",
  formSelect: "/form-select",
  formMask: "/form-mask",
  fileUpload: "/form-fileupload",
  horizontalForm: "/form-horizontal",
  verticalForm: "/form-vertical",
  floatingLable: "/form-floating-labels",
  formValidation: "/form-validation",
  reactSelect: "/select",
  formWizard: "/form-wizard",
  iconicIcon: "/icon-ionic",
  chartC3: "/chart-c3",
  chartMorris: "/chart-morris",
  chartFlot: "/chart-flot",
  chartPeity: "/chart-peity",


  //base-ui
  uiAlerts: "/ui-alerts",
  uiAccordion: "/ui-accordion",
  uiAvatar: "/ui-avatar",
  uiBadges: "/ui-badges",
  uiBorders: "/ui-borders",
  uiButtons: "/ui-buttons",
  uiButtonsGroup: "/ui-buttons-group",
  uiBreadcrumb: "/ui-breadcrumb",
  uiCards: "/ui-cards",
  uiCarousel: "/ui-carousel",
  uiCollapse: "/ui-collapse",
  uiColor: "/ui-color",
  uiDropdowns: "/ui-dropdowns",
  uiRatio: "/ui-ratio",
  uiGrid: "/ui-grid",
  uiImage: "/ui-image",
  uiLinks: "/ui-links",
  uiListGroup: "/ui-list-group",
  uiModals: "/ui-modals",
  uiScrollspy: "/ui-scrollspy",
  uiUtilities:"/ui-utilities",
  swiperjs: "/ui-swiperjs",
  sortable: "/ui-sortable",
  tablericons: "/icon-tabler",
  bootstrapicons: "/icon-bootstrap",
  remixicons: "/icon-remix",
  formpicker: "/form-pickers",
  mapleaflet: "/maps-leaflet",
  vectorMap: "/maps-vector",
  notificationbell:"/notifications",

  // pages routes
  error403: "/403",
  error404: "/error-404",
  error500: "/error-500",
  underMaintenance: "/under-maintenance",

  // inventory routes
  inventoryList: "/inventory",
  itemsList: "/items",
  addItem: "/items/new",
  itemOverview: "/items/:id",
  editItem: "/items/:id/edit",
  addOpeningStock: "/items/:id/opening-stock",
  compositeItems: "/composite-items",
  addCompositeItem: "/composite-items/new",
  compositeItemOverview: "/composite-items/:id",
  editCompositeItem: "/composite-items/:id/edit",
  locations: "/locations",
  locationOverview: "/locations/:id",
  addLocation: "/locations/new",
  editLocation: "/locations/:id/edit",
  transactionSeriesList: "/locations/series",
  transactionSeriesOverview: "/locations/series/:id",
  newTransactionSeries: "/locations/series/new",
  editTransactionSeries: "/locations/series/:seriesId/edit",
  priceList: "/price-list",
  newPriceList: "/price-list/new",
  priceListOverview: "/price-list/:id",
  editPriceList: "/price-list/:id/edit",
  assemblies: "/assemblies",
  newAssembly: "/assemblies/new",
  assemblyOverview: "/assemblies/:id",
  inventoryAdjustments: "/inventory-adjustments",
  newInventoryAdjustment: "/inventory-adjustments/new",
  inventoryAdjustmentOverview: "/inventory-adjustments/:id",
  transferOrders: "/transfer-orders",
  newTransferOrder: "/transfer-orders/new",
  transferOrderOverview: "/transfer-orders/:id",

  // customer routes
  distributionCategories:       "/distribution-categories",
  addDistributionCategory:      "/distribution-categories/new",
  editDistributionCategory:     "/distribution-categories/:id/edit",
  distributionSubCategories:    "/distribution-sub-categories",
  addDistributionSubCategory:   "/distribution-sub-categories/new",
  editDistributionSubCategory:  "/distribution-sub-categories/:id/edit",
  distributionLocationList:     "/distribution-locations",
  distributors:                 "/distributors",
  distributorOverview:          "/distributors/:id",
  addNewDistributors:           "/distributors/new",
  editDistributor:              "/distributors/:id/edit",

  // settings routes
  settingsHome: "/settings",
  productCustomField: "/app-settings/product-settings/add-custom-field",
  productCustomFieldEdit: "/app-settings/product-settings/edit-custom-field/:id",
  customerCustomField: "/app-settings/customer-settings/add-custom-field",
  customerCustomFieldEdit: "/app-settings/customer-settings/edit-custom-field/:id",
  customFields: "/app-settings/custom-fields",
  invoiceSettings: "/app-settings/invoice-settings",
  invoiceCustomField: "/app-settings/invoice-settings/add-custom-field",
  invoiceCustomFieldEdit: "/app-settings/invoice-settings/edit-custom-field/:id",
  printers: "/app-settings/printers",
  projectSettings: "/app-settings/project-settings",
  customerSettings: "/app-settings/customer-settings",
  paymentReceivedSettings: "/app-settings/payment-received-settings",
  paymentCustomField: "/app-settings/payment-received-settings/add-custom-field",
  paymentCustomFieldEdit: "/app-settings/payment-received-settings/edit-custom-field/:id",

  bankAccount: "/financial-settings/bank-ccount",
  currencies: "/financial-settings/currencies",
  paymentGateways: "/financial-settings/payment-gateways",
  taxRates: "/financial-settings/tax-rates",

  connectedApps: "/general-settings/connected-apps",
  notification: "/general-settings/notification",
  profile: "/profile",
  security: "/general-settings/security",

  banIpAddrress: "/other-settings/ban-ip-address",
  storage: "/other-settings/storage",
  sitemap: "/other-settings/sitemap",
  clearCache: "/other-settings/clear-cache",
  cronjob: "/other-settings/cronjob",
  systemBackup: "/other-settings/system-backup",
  databaseBackup: "/other-settings/database-backup",
  systemUpdate: "/other-settings/system-update",

  emailSettings: "/system-settings/storage",
  gdprCookies: "/system-settings/gdpr-cookies",
  smsGateways: "/system-settings/sms-gateways",

  appearance: "/website-settings/appearance",
  companySettings: "/website-settings/company-settings",
  language: "/website-settings/language",
  localization: "/website-settings/localization",
  preference: "/website-settings/preference",
  prefixes: "/website-settings/prefixes",
  languageWeb: "/website-settings/language-web",

  // reports routes
  companyReports: "/reports/company-reports",
  contactReports: "/reports/contact-reports",
  dealReports: "/reports/deal-reports",
  leadReports: "/reports/lead-reports",
  projectReports: "/reports/project-reports",
  taskReports: "/reports/task-reports",

  // application routes
  todo: "/application/todo",
  todoList: "/application/todo-List",
  email: "/application/email",
  emailReply: "/application/email-reply",
  videoCall: "/application/video-call",
  chat: "/application/chat",
  audioCall: "/application/audio-call",
  callHistory: "/application/call-history",
  fileManager: "/application/file-manager",
  socialfeed: "/application/social-feed",
  kanbanview: "/application/kanban-view",
  invoice: "/application/invoice",
  invoice_details: "/application/invoice-details",
  addInvoices:"/application/add-invoice",
  editInvoices:"/application/edit-invoice",

  // crmsetting routes
  sources: "/crm-setting/sources",
  contactStage: "/crm-setting/contact-stage",
  industry: "/crm-setting/industry",
  calls: "/crm-setting/calls",
  lostReason: "/crm-setting/lost-reason",

  //content routes
  pages: "/content/pages",
  addpages: "/content/add-pages",
  editpages: "/content/edit-pages",
  cities: "/content/cities",
  states: "/content/states",
  testimonials: "/content/testimonials",
  countries: "/content/countries",
  faq: "/content/faq",
  blog: "/content/blogs",
  addblog: "/content/add-blogs",
  editblog: "/content/edit-blogs",
  blogDetails: "/content/blog-details",
  blogComment: "/content/blog-comments",
  blogCategories: "/content/blog-categories",
  blogTags: "/content/blog-tags",

  //userManagement routes
  deleteRequest: "/user-management/delete-request",
  rolesPermissions: "/user-management/roles-permissions",
  newRole:          "/user-management/roles-permissions/new",
  roleOverview:     "/user-management/roles-permissions/:id",
  editRole:         "/user-management/roles-permissions/:id/edit",
  manageusers:  "/user-management/manage-users",
  newUser:      "/user-management/manage-users/new",
  editUser:     "/user-management/manage-users/:id/edit",
  userOverview: "/user-management/manage-users/:id",
  permissions: "/user-management/permissions",

  //support routes
  contactMessages: "/support/contact-messages",
  tickets: "/support/tickets",
  ticketsDetails: "/support/tickets-details",

  // membership routes
  membershipplan: "/membership-plans",
  membershipAddon: "/membership-addons",
  membershipTransaction: "/membership-transactions",

  //Layouts Pages
  layoutMini: "/layout-mini",
  hoverView: "/layout-hoverview",
  hidden: "/layout-hidden",
  fullWidth: "/layout-fullwidth",
  HorizontalSingle: "/layout-horizontal-single",
  WithoutHeader: "/layout-without-header",
  layoutRtl: "/layout-rtl",
  Detached: "/layout-detached",
  Dark: "/layout-dark",

  // Party portal routes
  partyLogin:             "/party/login",
  partyDashboard:         "/party/dashboard",
  partyItems:             "/party/items",
  partyItemDetail:        "/party/items/:id",
  partyCompositeItems:    "/party/composite-items",
  partyPriceList:         "/party/price-list",
};
