export const ItemsListData = [
  {
    id: 1,
    Name: "Dell UltraSharp Monitor",
    Type: "Goods",
    SKU: "ELEC-MON-001",
    Unit: "Nos",
    SellingPrice: "₹25,000",
    Status: "Active",
  },
  {
    id: 2,
    Name: "Mechanical Keyboard",
    Type: "Goods",
    SKU: "ELEC-KB-002",
    Unit: "Nos",
    SellingPrice: "₹4,500",
    Status: "Active",
  },
  {
    id: 3,
    Name: "Wireless Mouse",
    Type: "Goods",
    SKU: "ELEC-MS-003",
    Unit: "Nos",
    SellingPrice: "₹1,200",
    Status: "Active",
  },
  {
    id: 4,
    Name: "Annual Maintenance Contract",
    Type: "Service",
    SKU: "SVC-AMC-001",
    Unit: "Months",
    SellingPrice: "₹12,000",
    Status: "Active",
  },
  {
    id: 5,
    Name: "USB-C Hub 7-in-1",
    Type: "Goods",
    SKU: "ELEC-USB-004",
    Unit: "Nos",
    SellingPrice: "₹2,800",
    Status: "Active",
  },
  {
    id: 6,
    Name: "Laptop Stand Adjustable",
    Type: "Goods",
    SKU: "ACC-LPS-005",
    Unit: "Nos",
    SellingPrice: "₹1,500",
    Status: "Inactive",
  },
  {
    id: 7,
    Name: "Cloud Storage (1TB/yr)",
    Type: "Service",
    SKU: "SVC-CLO-002",
    Unit: "Years",
    SellingPrice: "₹3,600",
    Status: "Active",
  },
  {
    id: 8,
    Name: "Webcam HD 1080p",
    Type: "Goods",
    SKU: "ELEC-CAM-006",
    Unit: "Nos",
    SellingPrice: "₹3,200",
    Status: "Active",
  },
];
