import { all_routes } from "../../routes/all_routes";

const route = all_routes;
export const SidebarData = [
 {
    tittle: "Billing",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Items",
        link: route.itemsList,
        submenu: true,
        showSubRoute: false,
        icon: "package",
        base: "items",
        materialicons: "start",
        dot: true,
        permModule: "items",
        submenuItems: [
          { label: "Items",           link: route.itemsList,      permModule: "items" },
          { label: "Composite Items", link: route.compositeItems, permModule: "composite_items" },
          { label: "Price List",      link: route.priceList,      permModule: "price_list" },
        ],
      },
      {
        label: "Inventory",
        link: route.inventoryList,
        submenu: true,
        showSubRoute: false,
        icon: "box",
        base: "inventory",
        materialicons: "start",
        dot: true,
        permModule: "inventory",
        relatedRoutes: [
          route.inventoryList,
          route.assemblies,
          route.newAssembly,
          route.inventoryAdjustments,
          route.newInventoryAdjustment,
          route.transferOrders,
          route.newTransferOrder,
          route.transferOrderOverview,
        ],
        submenuItems: [
          { label: "Inventory",             link: route.inventoryList,         permModule: "inventory" },
          { label: "Assemblies",            link: route.assemblies,            permModule: "assemblies" },
          { label: "Inventory Adjustments", link: route.inventoryAdjustments,  permModule: "inventory_adjustments" },
          { label: "Transfer Orders",       link: route.transferOrders,        permModule: "transfer_orders" },
        ],
      },
      {
        label: "Sales",
        link: route.distributionCategories,
        submenu: true,
        showSubRoute: false,
        icon: "shopping-cart",
        base: "customers",
        materialicons: "start",
        dot: true,
        permModule: "parties",
        relatedRoutes: [
          route.distributionCategories,
          route.addDistributionCategory,
          route.distributors,
          route.distributorOverview,
          route.addNewDistributors,
          route.editDistributor,
          route.invoices,
          route.newInvoice,
          route.editInvoice,
          route.invoiceOverview,
          route.recordPayment,
          route.payments,
          route.newPayment,
          route.creditNotes,
          route.creditNoteOverview,
        ],
        submenuItems: [
          { label: "Parties",      link: route.distributors, permModule: "parties" },
          { label: "Invoices",     link: route.invoices,     permModule: "invoices" },
          { label: "Payments",     link: route.payments,     permModule: "payments" },
          { label: "Credit Notes", link: route.creditNotes,  permModule: "credit_notes" },
        ],
      },
      {
        label: "Others",
        link: route.distributionLocationList,
        submenu: true,
        showSubRoute: false,
        icon: "dots-circle-horizontal",
        base: "others",
        materialicons: "start",
        dot: true,
        permModule: "locations",
        relatedRoutes: [
          route.distributionLocationList,
          route.rolesPermissions,
          route.newRole,
          route.manageusers,
          route.newUser,
          route.userOverview,
        ],
        submenuItems: [
          { label: "Distribution Locations", link: route.distributionLocationList, permModule: "locations" },
          { label: "Roles & Permissions",    link: route.rolesPermissions,         permModule: "roles" },
          { label: "Users",                  link: route.manageusers,              permModule: "users" },
        ],
      },
    ],
  },
];
